### PR TITLE
Add init file to ions package, re-export classes

### PR DESCRIPTION
**Pull request by lochsh**
There was a missing `__init__.py` file in the `ions` package. I've added one, and re-exported the ion classes so that you can do e.g. 

```python
from atomic_physics import ions

ions.Ca40()
```

or

```python
import atomic_physics.ions

atomic_physics.ions.Ca40()
```

### CODE REVIEW

**Review by dnadlinger — APPROVED** [review]
Thanks!

**Comment by lochsh** [comment]
Thank you :slightly_smiling_face: I understand this is released on pypi.org, is it possible to do a release with this change?

**Comment by dnadlinger** [comment]
I've never actually done this for `atomic_physics`. @hartytp: Is the idea behind the package workflow that it just always runs, but fails unless the version actually is incremented? (in which case a new release would then just be a matter of bumping the version number in a PR)

**Comment by lochsh** [comment]
>IIRC pypi ignores the version string in pyproject and goes based on the git tag. IIRC the workflow is "push a tag and then cut a release"

There are no tags though https://github.com/OxfordIonTrapGroup/atomic_physics/tags so it doesn't seem like this is how you've done it?

**Comment by hartytp** [comment]
Thanks for the correction @lochsh, I was thinking of another project. Here we do seem to go from pyproject, so it's exactly as @dnadlinger described above. Apologies for the confusion

**Pull request merged**
